-- MySQL Script generated by MySQL Workbench
-- 06/14/18 03:01:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Juego` ;

CREATE TABLE IF NOT EXISTS `Juego` (
  `idJuego` INT NOT NULL DEFAULT auto_increment,
  `nombreJuego` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(350) NOT NULL,
  `promedio` FLOAT NOT NULL,
  `stock` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  `consola` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(260) NOT NULL,
  `linkVideo` VARCHAR(260) NULL,
  `genero` VARCHAR(45) NOT NULL,
  `empresaDesarrolladora` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idJuego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Persona` ;

CREATE TABLE IF NOT EXISTS `Persona` (
  `idPersona` INT NOT NULL DEFAULT auto_increment,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(320) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cuenta` ;

CREATE TABLE IF NOT EXISTS `Cuenta` (
  `usuario` VARCHAR(30) NOT NULL,
  `contrasena` VARCHAR(64) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`usuario`),
  INDEX `fk_Cuenta_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Cuenta_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido` ;

CREATE TABLE IF NOT EXISTS `Pedido` (
  `idPedido` INT NOT NULL DEFAULT auto_increment,
  `cantidadJuegos` INT NOT NULL,
  `fechaApartado` DATE NOT NULL,
  `fechaLimite` DATE NOT NULL,
  `precioTotal` FLOAT NOT NULL,
  `fechaPago` DATE NULL,
  `estatus` VARCHAR(15) NOT NULL,
  `idJuego` INT NOT NULL,
  `usuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Juego1_idx` (`idJuego` ASC),
  INDEX `fk_Pedido_Cuenta1_idx` (`usuario` ASC),
  CONSTRAINT `fk_Pedido_Juego1`
    FOREIGN KEY (`idJuego`)
    REFERENCES `Juego` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cuenta1`
    FOREIGN KEY (`usuario`)
    REFERENCES `Cuenta` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL DEFAULT auto_increment,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(320) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
